import { Product, Category, Brand } from "@/types"

const img = (id: number) => `https://picsum.photos/seed/${id}/400/400`
const img2 = (id: number) => `https://picsum.photos/seed/${id}a/400/400`
const img3 = (id: number) => `https://picsum.photos/seed/${id}b/400/400`

export const categories: Category[] = [
  { id: "1", name: "Skincare", image: "/images/skincare.jpg", itemCount: 245 },
  { id: "2", name: "Makeup", image: "/images/makeup.jpg", itemCount: 189 },
  { id: "3", name: "Hair Care", image: "/images/haircare.jpg", itemCount: 134 },
  { id: "4", name: "Body Care", image: "/images/bodycare.jpg", itemCount: 98 },
  { id: "5", name: "Sunscreen", image: "/images/sunscreen.jpg", itemCount: 67 },
  { id: "6", name: "Fragrance", image: "/images/fragrance.jpg", itemCount: 112 },
  { id: "7", name: "Korean Beauty", image: "/images/kbeauty.jpg", itemCount: 203 },
]

export const brands: Brand[] = [
  { id: "1", name: "GlowLab", logo: "/images/glowlab.png", description: "Premium Korean skincare" },
  { id: "2", name: "DewySkin", logo: "/images/dewyskin.png", description: "Hydration experts" },
  { id: "3", name: "PureGlow", logo: "/images/pureglow.png", description: "Clean beauty" },
  { id: "4", name: "VelvetTouch", logo: "/images/velvettouch.png", description: "Luxury makeup" },
  { id: "5", name: "BloomEssentials", logo: "/images/bloom.png", description: "Natural ingredients" },
  { id: "6", name: "RadianceCo", logo: "/images/radiance.png", description: "Brightening solutions" },
]

export const products: Product[] = [
  {
    id: "p1", name: "Vitamin C Brightening Serum", brand: "GlowLab",
    category: "Skincare", subCategory: "Serums",
    description: "A potent vitamin C serum that brightens skin, reduces dark spots, and evens out skin tone. Formulated with 15% pure Vitamin C, Vitamin E, and Ferulic Acid for maximum antioxidant protection.",
    ingredients: "Ascorbic Acid (Vitamin C), Tocopherol (Vitamin E), Ferulic Acid, Hyaluronic Acid, Aloe Vera, Glycerin",
    benefits: ["Brightens skin tone", "Reduces dark spots", "Boosts collagen", "Antioxidant protection"],
    howToUse: "Apply 3-4 drops to clean, dry face after cleansing. Follow with moisturizer and sunscreen. Use morning and evening.",
    price: 38, originalPrice: 52, discount: 27,
    rating: 4.8, reviewCount: 2453,
    images: [img(101), img2(101), img3(101)],
    videos: [],
    skinType: ["All", "Normal", "Oily", "Combination"],
    productType: "Serum", stock: 50, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: true, flashSaleEnds: "2026-07-03T23:59:59",
    tags: ["vitamin c", "brightening", "serum", "antioxidant"]
  },
  {
    id: "p2", name: "Hyaluronic Acid Moisture Cream", brand: "DewySkin",
    category: "Skincare", subCategory: "Moisturizers",
    description: "Ultra-hydrating moisturizer with triple hyaluronic acid complex. Provides deep, lasting hydration without feeling heavy.",
    ingredients: "Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Ceramides, Squalane, Shea Butter, Panthenol",
    benefits: ["Deep hydration", "Strengthens skin barrier", "Plumps skin", "Soothes irritation"],
    howToUse: "Apply generously to face and neck after serum. Use morning and evening.",
    price: 34, originalPrice: 45, discount: 24,
    rating: 4.7, reviewCount: 1821,
    images: [img(102), img2(102), img3(102)],
    videos: [],
    skinType: ["All", "Dry", "Normal", "Sensitive"],
    productType: "Moisturizer", stock: 35, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: true, flashSaleEnds: "2026-07-04T23:59:59",
    tags: ["hyaluronic acid", "moisturizer", "hydration", "cream"]
  },
  {
    id: "p3", name: "Retinol Night Renewal Oil", brand: "GlowLab",
    category: "Skincare", subCategory: "Oils",
    description: "A lightweight retinol oil that works overnight to reduce fine lines, wrinkles, and improve skin texture. Formulated with encapsulated retinol for gradual release.",
    ingredients: "Retinol, Jojoba Oil, Rosehip Oil, Vitamin E, Bakuchiol, CoQ10",
    benefits: ["Reduces fine lines", "Improves texture", "Even tone", "Overnight renewal"],
    howToUse: "Apply 2-3 drops to face after cleansing. Use only at night. Start with 2-3 times per week.",
    price: 48, originalPrice: 65, discount: 26,
    rating: 4.6, reviewCount: 987,
    images: [img(103), img2(103)],
    videos: [],
    skinType: ["Normal", "Combination", "Oily"],
    productType: "Oil", stock: 25, isNew: true, isBestSeller: false, isTrending: true, isFlashSale: true, flashSaleEnds: "2026-07-02T23:59:59",
    tags: ["retinol", "night oil", "anti-aging", "wrinkles"]
  },
  {
    id: "p4", name: "Gentle Cica Cleansing Foam", brand: "PureGlow",
    category: "Skincare", subCategory: "Cleansers",
    description: "pH-balanced foaming cleanser with Centella Asiatica (Cica) to calm and cleanse sensitive skin without stripping natural oils.",
    ingredients: "Centella Asiatica Extract, Tea Tree Oil, Salicylic Acid, Aloe Vera, Green Tea Extract",
    benefits: ["Calms irritation", "Removes impurities", "pH balanced", "Non-stripping"],
    howToUse: "Dispense 1-2 pumps, lather with water, massage onto face, rinse thoroughly. Use morning and evening.",
    price: 22, originalPrice: 28, discount: 21,
    rating: 4.5, reviewCount: 1532,
    images: [img(104), img2(104)],
    videos: [],
    skinType: ["All", "Sensitive", "Dry"],
    productType: "Cleanser", stock: 60, isNew: true, isBestSeller: false, isTrending: true, isFlashSale: false,
    tags: ["cica", "cleanser", "sensitive", "calming"]
  },
  {
    id: "p5", name: "Matte Liquid Lipstick - Rose Petal", brand: "VelvetTouch",
    category: "Makeup", subCategory: "Lips",
    description: "Long-wearing matte liquid lipstick with a comfortable, non-drying formula. Stays put for up to 12 hours without feathering.",
    ingredients: "Dimethicone, Vitamin E, Jojoba Oil, Shea Butter, Aloe Vera",
    benefits: ["12hr wear", "Non-drying", "Transfer-proof", "Comfortable matte"],
    howToUse: "Apply directly to lips. Allow 30 seconds to dry for transfer-proof finish.",
    price: 18, originalPrice: 24, discount: 25,
    rating: 4.4, reviewCount: 3210,
    images: [img(105), img2(105)],
    videos: [],
    skinType: ["All"],
    productType: "Lipstick", stock: 80, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: true, flashSaleEnds: "2026-07-04T23:59:59",
    tags: ["lipstick", "matte", "long-wear", "rose"]
  },
  {
    id: "p6", name: "Dewy Skin Tint SPF 30", brand: "DewySkin",
    category: "Makeup", subCategory: "Base",
    description: "Light-coverage skin tint with SPF 30 for a natural dewy finish. Evens out skin tone while protecting from sun damage.",
    ingredients: "Zinc Oxide, Niacinamide, Hyaluronic Acid, Vitamin C, Aloe Vera",
    benefits: ["Light coverage", "Sun protection", "Dewy finish", "Skin benefits"],
    howToUse: "Shake well. Apply with fingers or brush to face after moisturizer. Build as needed.",
    price: 32, originalPrice: 40, discount: 20,
    rating: 4.6, reviewCount: 1876,
    images: [img(106), img2(106)],
    videos: [],
    skinType: ["All", "Normal", "Combination", "Dry"],
    productType: "Tint", stock: 45, isNew: true, isBestSeller: false, isTrending: true, isFlashSale: false,
    tags: ["skin tint", "spf", "dewy", "light coverage"]
  },
  {
    id: "p7", name: "Hair Repair Bond Treatment", brand: "BloomEssentials",
    category: "Hair Care", subCategory: "Treatments",
    description: "Bond-repairing treatment that rebuilds damaged hair from within. Restores strength, shine, and elasticity.",
    ingredients: "Hydrolyzed Keratin, Argan Oil, Biotin, Silk Proteins, Vitamin B5",
    benefits: ["Repairs bonds", "Reduces breakage", "Adds shine", "Strengthens hair"],
    howToUse: "Apply to damp clean hair. Leave for 10 minutes. Rinse thoroughly. Use 1-2 times per week.",
    price: 28, originalPrice: 36, discount: 22,
    rating: 4.7, reviewCount: 1456,
    images: [img(107), img2(107)],
    videos: [],
    skinType: ["All"],
    productType: "Treatment", stock: 30, isNew: true, isBestSeller: false, isTrending: false, isFlashSale: false,
    tags: ["hair treatment", "bond repair", "keratin", "damaged hair"]
  },
  {
    id: "p8", name: "Radiance Eye Cream with Caffeine", brand: "RadianceCo",
    category: "Skincare", subCategory: "Eye Care",
    description: "Brightening eye cream with caffeine and niacinamide to reduce dark circles, puffiness, and fine lines around the eyes.",
    ingredients: "Caffeine, Niacinamide, Peptides, Hyaluronic Acid, Vitamin C, Licorice Root",
    benefits: ["Reduces dark circles", "Depuffs", "Brightens", "Smooths fine lines"],
    howToUse: "Dot a small amount under eyes and gently tap with ring finger. Use morning and evening.",
    price: 36, originalPrice: 48, discount: 25,
    rating: 4.5, reviewCount: 876,
    images: [img(108), img2(108)],
    videos: [],
    skinType: ["All", "Normal", "Dry", "Combination"],
    productType: "Eye Cream", stock: 40, isNew: false, isBestSeller: true, isTrending: false, isFlashSale: false,
    tags: ["eye cream", "caffeine", "dark circles", "puffiness"]
  },
  {
    id: "p9", name: "Korean Rice Brightening Toner", brand: "GlowLab",
    category: "Korean Beauty", subCategory: "Toners",
    description: "Traditional Korean rice toner that brightens and smooths skin texture. Fermented rice water extracts for radiant glass skin.",
    ingredients: "Fermented Rice Water, Niacinamide, Sake Extract, Glycerin, Green Tea",
    benefits: ["Brightens complexion", "Smooths texture", "Hydrates", "Soothes"],
    howToUse: "Apply to face after cleansing using hands or cotton pad. Pat gently for absorption.",
    price: 26, originalPrice: 34, discount: 24,
    rating: 4.8, reviewCount: 2341,
    images: [img(109), img2(109)],
    videos: [],
    skinType: ["All", "Normal", "Combination", "Oily"],
    productType: "Toner", stock: 55, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: true, flashSaleEnds: "2026-07-05T23:59:59",
    tags: ["k-beauty", "rice toner", "brightening", "fermented"]
  },
  {
    id: "p10", name: "Sunscreen SPF 50+ PA++++", brand: "PureGlow",
    category: "Sunscreen", subCategory: "Face Sunscreen",
    description: "Lightweight invisible sunscreen with SPF 50+ PA++++. No white cast, absorbs quickly, works perfectly under makeup.",
    ingredients: "Avobenzone, Homosalate, Octisalate, Niacinamide, Hyaluronic Acid, Vitamin E",
    benefits: ["Highest UV protection", "No white cast", "Lightweight", "Makeup-friendly"],
    howToUse: "Apply generously to face and neck 15 minutes before sun exposure. Reapply every 2 hours.",
    price: 24, originalPrice: 30, discount: 20,
    rating: 4.7, reviewCount: 3214,
    images: [img(110), img2(110)],
    videos: [],
    skinType: ["All", "Normal", "Oily", "Combination"],
    productType: "Sunscreen", stock: 70, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: false,
    tags: ["sunscreen", "spf 50", "pa++++", "no white cast"]
  },
  {
    id: "p11", name: "Rose Water Hydrating Mist", brand: "BloomEssentials",
    category: "Skincare", subCategory: "Mists",
    description: "100% natural rose water mist to refresh, hydrate, and soothe skin throughout the day. Perfect for setting makeup.",
    ingredients: "Rosa Damascena Flower Water, Glycerin, Aloe Vera",
    benefits: ["Instantly hydrates", "Refreshes skin", "Soothes redness", "Sets makeup"],
    howToUse: "Mist onto face as needed throughout the day. Use after cleansing or to set makeup.",
    price: 14, originalPrice: 18, discount: 22,
    rating: 4.4, reviewCount: 1654,
    images: [img(111), img2(111)],
    videos: [],
    skinType: ["All", "Sensitive", "Dry", "Normal"],
    productType: "Mist", stock: 90, isNew: false, isBestSeller: false, isTrending: false, isFlashSale: false,
    tags: ["rose water", "mist", "hydrating", "natural"]
  },
  {
    id: "p12", name: "Shea & Vanilla Body Butter", brand: "BloomEssentials",
    category: "Body Care", subCategory: "Body Moisturizers",
    description: "Rich whipped body butter with shea butter and vanilla for deep lasting moisture with a warm comforting vanilla scent.",
    ingredients: "Shea Butter, Cocoa Butter, Coconut Oil, Vanilla Extract, Vitamin E",
    benefits: ["Deep moisture", "Nourishes skin", "Natural scent", "Non-greasy"],
    howToUse: "Apply to clean dry skin after bath. Massage in circular motions until absorbed.",
    price: 20, originalPrice: 26, discount: 23,
    rating: 4.6, reviewCount: 2134,
    images: [img(112), img2(112)],
    videos: [],
    skinType: ["All", "Dry", "Normal"],
    productType: "Body Butter", stock: 65, isNew: false, isBestSeller: true, isTrending: false, isFlashSale: true, flashSaleEnds: "2026-07-06T23:59:59",
    tags: ["body butter", "shea", "vanilla", "moisturizer"]
  },
  {
    id: "p13", name: "Peptide Lip Treatment", brand: "RadianceCo",
    category: "Makeup", subCategory: "Lips",
    description: "Plumping lip treatment with peptides and hyaluronic acid for smoother, fuller-looking lips with a high-shine finish.",
    ingredients: "Peptides, Hyaluronic Acid, Squalane, Castor Oil, Vitamin E",
    benefits: ["Plumps lips", "Hydrates", "Smooths lines", "High-shine finish"],
    howToUse: "Apply to lips as needed. Use alone or over lipstick for added shine.",
    price: 16, originalPrice: 20, discount: 20,
    rating: 4.3, reviewCount: 987,
    images: [img(113), img2(113)],
    videos: [],
    skinType: ["All"],
    productType: "Lip Treatment", stock: 75, isNew: true, isBestSeller: false, isTrending: true, isFlashSale: false,
    tags: ["lip treatment", "peptide", "plumping", "hydration"]
  },
  {
    id: "p14", name: "Hyaluronic Acid Sheet Mask 10pk", brand: "DewySkin",
    category: "Skincare", subCategory: "Masks",
    description: "Sheet masks soaked in hyaluronic acid essence for an instant hydration boost. Leaves skin plump and dewy with each use.",
    ingredients: "Hyaluronic Acid, Ceramides, Glycerin, Aloe Vera, Panthenol",
    benefits: ["Instant hydration", "Plumps skin", "Calms skin", "Refreshes"],
    howToUse: "Apply mask to clean face. Leave for 15-20 minutes. Remove and pat in remaining essence.",
    price: 28, originalPrice: 40, discount: 30,
    rating: 4.5, reviewCount: 4567,
    images: [img(114), img2(114)],
    videos: [],
    skinType: ["All", "Dry", "Normal", "Dehydrated"],
    productType: "Mask", stock: 200, isNew: false, isBestSeller: false, isTrending: false, isFlashSale: true, flashSaleEnds: "2026-07-06T23:59:59",
    tags: ["sheet mask", "hyaluronic acid", "hydrating", "essence"]
  },
  {
    id: "p15", name: "Lash Growth Serum", brand: "GlowLab",
    category: "Makeup", subCategory: "Eyes",
    description: "Advanced lash growth serum with peptides and biotin that promotes longer, thicker lashes in just 4 weeks.",
    ingredients: "Peptides, Biotin, Castor Oil, Panthenol, Ginseng Extract",
    benefits: ["Lengthens lashes", "Thickens lashes", "Nourishes", "Results in 4 weeks"],
    howToUse: "Apply a thin line along upper lash line once daily at night.",
    price: 42, originalPrice: 55, discount: 24,
    rating: 4.6, reviewCount: 2789,
    images: [img(115), img2(115)],
    videos: [],
    skinType: ["All"],
    productType: "Serum", stock: 40, isNew: false, isBestSeller: true, isTrending: false, isFlashSale: false,
    tags: ["lash serum", "growth", "peptide", "eyelash"]
  },
  {
    id: "p16", name: "Niacinamide 10% + Zinc Serum", brand: "PureGlow",
    category: "Skincare", subCategory: "Serums",
    description: "High-strength niacinamide serum with zinc to control oil, minimize pores, and improve skin texture and tone.",
    ingredients: "Niacinamide, Zinc PCA, Hyaluronic Acid, Green Tea Extract, Aloe Vera",
    benefits: ["Minimizes pores", "Controls oil", "Improves texture", "Evens tone"],
    howToUse: "Apply a few drops to face after cleansing and before moisturizer. Use morning and evening.",
    price: 20, originalPrice: 28, discount: 29,
    rating: 4.6, reviewCount: 3120,
    images: [img(116), img2(116)],
    videos: [],
    skinType: ["Oily", "Combination", "Normal"],
    productType: "Serum", stock: 85, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: false,
    tags: ["niacinamide", "zinc", "pores", "oil control"]
  },
  {
    id: "p17", name: "Snail Mucin 96% Essence", brand: "GlowLab",
    category: "Korean Beauty", subCategory: "Essences",
    description: "Powerful snail mucin essence that repairs, hydrates and rejuvenates skin. A K-beauty cult favorite for glass skin.",
    ingredients: "Snail Secretion Filtrate 96%, Hyaluronic Acid, Panthenol, Allantoin",
    benefits: ["Repairs skin barrier", "Deep hydration", "Soothes inflammation", "Anti-aging"],
    howToUse: "Apply 1-2 pumps to face after toner. Pat gently for absorption. Follow with moisturizer.",
    price: 22, originalPrice: 30, discount: 27,
    rating: 4.8, reviewCount: 5678,
    images: [img(117), img2(117), img3(117)],
    videos: [],
    skinType: ["All", "Dry", "Sensitive", "Dehydrated"],
    productType: "Essence", stock: 70, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: true, flashSaleEnds: "2026-07-07T23:59:59",
    tags: ["snail mucin", "k-beauty", "essence", "repair"]
  },
  {
    id: "p18", name: "Vitamin E Nourishing Hair Oil", brand: "BloomEssentials",
    category: "Hair Care", subCategory: "Oils",
    description: "Lightweight hair oil with Vitamin E and argan oil that nourishes dry ends, tames frizz, and adds brilliant shine.",
    ingredients: "Vitamin E, Argan Oil, Jojoba Oil, Coconut Oil, Rosemary Extract",
    benefits: ["Nourishes ends", "Tames frizz", "Adds shine", "Lightweight"],
    howToUse: "Apply 2-3 drops to damp or dry hair, focusing on ends. Style as usual.",
    price: 18, originalPrice: 24, discount: 25,
    rating: 4.4, reviewCount: 1234,
    images: [img(118), img2(118)],
    videos: [],
    skinType: ["All"],
    productType: "Oil", stock: 55, isNew: true, isBestSeller: false, isTrending: false, isFlashSale: false,
    tags: ["hair oil", "vitamin e", "argan", "frizz control"]
  },
  {
    id: "p19", name: "Volumizing Mascara - Black", brand: "VelvetTouch",
    category: "Makeup", subCategory: "Eyes",
    description: "Intense black volumizing mascara with a unique hourglass brush that coats every lash for dramatic volume and length.",
    ingredients: "Beeswax, Carnauba Wax, Vitamin B5, Keratin, Iron Oxides",
    benefits: ["Dramatic volume", "Lengthens", "Smudge-proof", "All-day wear"],
    howToUse: "Wiggle brush from root to tip. Layer for more volume. Remove with micellar water.",
    price: 22, originalPrice: 28, discount: 21,
    rating: 4.5, reviewCount: 2890,
    images: [img(119), img2(119)],
    videos: [],
    skinType: ["All"],
    productType: "Mascara", stock: 90, isNew: false, isBestSeller: false, isTrending: true, isFlashSale: false,
    tags: ["mascara", "volumizing", "lashes", "makeup"]
  },
  {
    id: "p20", name: "Body Scrub - Coffee & Coconut", brand: "BloomEssentials",
    category: "Body Care", subCategory: "Exfoliators",
    description: "Energizing body scrub with finely ground coffee and coconut oil that exfoliates, smooths, and invigorates skin.",
    ingredients: "Coffee Grounds, Coconut Oil, Brown Sugar, Vitamin E, Shea Butter",
    benefits: ["Exfoliates", "Smooths skin", "Boosts circulation", "Natural ingredients"],
    howToUse: "Massage onto damp skin in circular motions. Rinse thoroughly. Use 2-3 times per week.",
    price: 24, originalPrice: 32, discount: 25,
    rating: 4.6, reviewCount: 1876,
    images: [img(120), img2(120)],
    videos: [],
    skinType: ["All", "Normal", "Dry"],
    productType: "Scrub", stock: 45, isNew: true, isBestSeller: true, isTrending: false, isFlashSale: false,
    tags: ["body scrub", "coffee", "coconut", "exfoliator"]
  },
  {
    id: "p21", name: "Green Tea Matte Moisturizer", brand: "PureGlow",
    category: "Skincare", subCategory: "Moisturizers",
    description: "Oil-free matte moisturizer with green tea that hydrates without greasiness. Perfect for oily and acne-prone skin.",
    ingredients: "Green Tea Extract, Salicylic Acid, Niacinamide, Zinc PCA, Aloe Vera",
    benefits: ["Oil-free hydration", "Matter finish", "Reduces breakouts", "Calms skin"],
    howToUse: "Apply a pea-sized amount to face after serum. Use morning and evening.",
    price: 26, originalPrice: 34, discount: 24,
    rating: 4.4, reviewCount: 1456,
    images: [img(121), img2(121)],
    videos: [],
    skinType: ["Oily", "Combination", "Acne-prone"],
    productType: "Moisturizer", stock: 60, isNew: false, isBestSeller: false, isTrending: true, isFlashSale: false,
    tags: ["green tea", "matte", "moisturizer", "oil-free"]
  },
  {
    id: "p22", name: "Setting Spray - Dewy Finish", brand: "VelvetTouch",
    category: "Makeup", subCategory: "Setting",
    description: "Micro-fine setting spray that locks in makeup for 16 hours while giving a natural dewy glow.",
    ingredients: "Water, Glycerin, Aloe Vera, Green Tea Extract, Vitamin B5",
    benefits: ["16hr wear", "Dewy finish", "Locks makeup", "Hydrates"],
    howToUse: "Hold 8 inches from face. Mist in an X and T pattern. Let air dry.",
    price: 16, originalPrice: 20, discount: 20,
    rating: 4.3, reviewCount: 2340,
    images: [img(122), img2(122)],
    videos: [],
    skinType: ["All"],
    productType: "Spray", stock: 100, isNew: true, isBestSeller: false, isTrending: true, isFlashSale: false,
    tags: ["setting spray", "dewy", "makeup", "long-lasting"]
  },
  {
    id: "p23", name: "AHA BHA Exfoliating Toner", brand: "GlowLab",
    category: "Skincare", subCategory: "Toners",
    description: "Dual-action exfoliating toner with AHA and BHA that unclogs pores, smooths texture, and reveals brighter skin.",
    ingredients: "Glycolic Acid, Salicylic Acid, Lactic Acid, Aloe Vera, Panthenol",
    benefits: ["Unclogs pores", "Smooths texture", "Brightens", "Exfoliates"],
    howToUse: "Apply with cotton pad to face after cleansing. Use only in PM. Start 2-3 times per week.",
    price: 24, originalPrice: 32, discount: 25,
    rating: 4.5, reviewCount: 2156,
    images: [img(123), img2(123)],
    videos: [],
    skinType: ["Normal", "Combination", "Oily"],
    productType: "Toner", stock: 45, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: false,
    tags: ["aha", "bha", "exfoliating", "toner"]
  },
  {
    id: "p24", name: "Squalane Cleansing Balm", brand: "DewySkin",
    category: "Skincare", subCategory: "Cleansers",
    description: "Silky cleansing balm with squalane that melts away makeup, sunscreen, and impurities without stripping the skin.",
    ingredients: "Squalane, Jojoba Oil, Vitamin E, Green Tea, Chamomile Extract",
    benefits: ["Removes makeup", "Dissolves sunscreen", "Non-stripping", "Nourishes"],
    howToUse: "Scoop a pea-sized amount. Massage onto dry face. Add water to emulsify. Rinse.",
    price: 30, originalPrice: 38, discount: 21,
    rating: 4.7, reviewCount: 1890,
    images: [img(124), img2(124)],
    videos: [],
    skinType: ["All", "Dry", "Normal", "Sensitive"],
    productType: "Cleanser", stock: 40, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: false,
    tags: ["cleansing balm", "squalane", "makeup remover", "oil cleanser"]
  },
  {
    id: "p25", name: "Rosehip Brightening Oil", brand: "RadianceCo",
    category: "Skincare", subCategory: "Oils",
    description: "Cold-pressed rosehip seed oil rich in essential fatty acids and vitamin C to brighten, repair, and rejuvenate.",
    ingredients: "Rosa Canina Seed Oil, Vitamin C, Lycopene, Beta-Carotene, Vitamin E",
    benefits: ["Brightens skin", "Reduces scars", "Anti-aging", "Nourishes"],
    howToUse: "Apply 2-3 drops to face after cleansing. Can be mixed with moisturizer. Use AM and PM.",
    price: 32, originalPrice: 42, discount: 24,
    rating: 4.5, reviewCount: 1678,
    images: [img(125), img2(125)],
    videos: [],
    skinType: ["All", "Dry", "Normal", "Mature"],
    productType: "Oil", stock: 35, isNew: false, isBestSeller: false, isTrending: true, isFlashSale: false,
    tags: ["rosehip", "oil", "brightening", "vitamin c"]
  },
  {
    id: "p26", name: "Matte Bronzer Powder - Warm Tan", brand: "VelvetTouch",
    category: "Makeup", subCategory: "Face",
    description: "Silky matte bronzer that gives a natural sun-kissed warmth to the face. Buildable color with a smooth blendable texture.",
    ingredients: "Mica, Talc, Zinc Stearate, Vitamin E, Jojoba Oil",
    benefits: ["Natural tan", "Buildable", "Matte finish", "Blends easily"],
    howToUse: "Brush onto cheeks, forehead, and jawline where the sun naturally hits.",
    price: 26, originalPrice: 34, discount: 24,
    rating: 4.4, reviewCount: 1432,
    images: [img(126), img2(126)],
    videos: [],
    skinType: ["All"],
    productType: "Bronzer", stock: 55, isNew: true, isBestSeller: false, isTrending: false, isFlashSale: false,
    tags: ["bronzer", "matte", "face", "contour"]
  },
  {
    id: "p27", name: "Cica Sleeping Mask", brand: "PureGlow",
    category: "Skincare", subCategory: "Masks",
    description: "Overnight sleeping mask with Centella Asiatica that calms, repairs, and hydrates while you sleep for refreshed skin by morning.",
    ingredients: "Centella Asiatica, Madecassoside, Hyaluronic Acid, Ceramides, Squalane",
    benefits: ["Overnight repair", "Calms redness", "Deep hydration", "Restores barrier"],
    howToUse: "Apply a generous layer to face as last step of PM routine. Leave overnight. Rinse in AM.",
    price: 26, originalPrice: 35, discount: 26,
    rating: 4.6, reviewCount: 2134,
    images: [img(127), img2(127)],
    videos: [],
    skinType: ["All", "Sensitive", "Dry", "Irritated"],
    productType: "Mask", stock: 50, isNew: false, isBestSeller: true, isTrending: false, isFlashSale: true, flashSaleEnds: "2026-07-08T23:59:59",
    tags: ["sleeping mask", "cica", "centella", "overnight"]
  },
  {
    id: "p28", name: "Sakura Body Lotion", brand: "DewySkin",
    category: "Body Care", subCategory: "Body Moisturizers",
    description: "Lightweight cherry blossom scented body lotion that hydrates and leaves skin delicately fragranced with a subtle floral scent.",
    ingredients: "Cherry Blossom Extract, Shea Butter, Glycerin, Vitamin E, Jojoba Oil",
    benefits: ["Lightweight hydration", "Floral scent", "Soft skin", "Quick absorption"],
    howToUse: "Apply liberally to body after shower. Massage until fully absorbed.",
    price: 18, originalPrice: 24, discount: 25,
    rating: 4.5, reviewCount: 1678,
    images: [img(128), img2(128)],
    videos: [],
    skinType: ["All", "Normal", "Dry"],
    productType: "Lotion", stock: 80, isNew: true, isBestSeller: false, isTrending: false, isFlashSale: false,
    tags: ["body lotion", "sakura", "cherry blossom", "hydrating"]
  },
  {
    id: "p29", name: "Lip Sleeping Mask - Berry", brand: "GlowLab",
    category: "Korean Beauty", subCategory: "Lips",
    description: "K-beauty lip sleeping mask with berry extracts that softens, smooths, and hydrates lips overnight.",
    ingredients: "Shea Butter, Jojoba Oil, Berry Extracts, Vitamin C, Hyaluronic Acid",
    benefits: ["Overnight treatment", "Softens lips", "Smooths lines", "Berry scent"],
    howToUse: "Apply a generous layer to lips before bed. Wipe off excess in the morning.",
    price: 16, originalPrice: 22, discount: 27,
    rating: 4.7, reviewCount: 3456,
    images: [img(129), img2(129)],
    videos: [],
    skinType: ["All"],
    productType: "Mask", stock: 95, isNew: false, isBestSeller: true, isTrending: true, isFlashSale: false,
    tags: ["lip mask", "sleeping mask", "k-beauty", "berry"]
  },
  {
    id: "p30", name: "Mineral Sunstick SPF 50", brand: "PureGlow",
    category: "Sunscreen", subCategory: "Face Sunscreen",
    description: "Convenient mineral sunstick with SPF 50 for easy reapplication throughout the day. Transparent finish, perfect for on-the-go.",
    ingredients: "Zinc Oxide, Titanium Dioxide, Shea Butter, Vitamin E, Green Tea",
    benefits: ["Easy reapplication", "Transparent", "Mineral formula", "Travel-friendly"],
    howToUse: "Swip directly onto face and neck. Blend with fingers if needed. Reapply every 2 hours.",
    price: 18, originalPrice: 24, discount: 25,
    rating: 4.3, reviewCount: 987,
    images: [img(130), img2(130)],
    videos: [],
    skinType: ["All", "Sensitive", "Normal"],
    productType: "Sunscreen", stock: 65, isNew: true, isBestSeller: false, isTrending: false, isFlashSale: false,
    tags: ["sunstick", "spf 50", "mineral", "travel"]
  },
  {
    id: "p31", name: "Hydrating Face Mist - Cucumber", brand: "DewySkin",
    category: "Skincare", subCategory: "Mists",
    description: "Refreshing face mist with cucumber and aloe that instantly cools, hydrates, and revitalizes tired skin.",
    ingredients: "Cucumber Extract, Aloe Vera, Glycerin, Allantoin, Panthenol",
    benefits: ["Instantly cools", "Refreshes skin", "Hydrates", "Revitalizes"],
    howToUse: "Mist onto face whenever skin needs a refresh. Use after cleansing or throughout the day.",
    price: 12, originalPrice: 16, discount: 25,
    rating: 4.2, reviewCount: 1234,
    images: [img(131), img2(131)],
    videos: [],
    skinType: ["All", "Normal", "Oily", "Combination"],
    productType: "Mist", stock: 120, isNew: true, isBestSeller: false, isTrending: false, isFlashSale: false,
    tags: ["face mist", "cucumber", "hydrating", "refresh"]
  },
  {
    id: "p32", name: "Perfume - White Jasmine", brand: "RadianceCo",
    category: "Fragrance", subCategory: "Eau de Parfum",
    description: "Elegant white jasmine perfume with notes of jasmine petals, vanilla musk, and sandalwood. Long-lasting floral fragrance.",
    ingredients: "Alcohol Denat, Parfum, Jasmine Extract, Vanilla, Sandalwood Oil",
    benefits: ["Long-lasting", "Floral scent", "Elegant", "Day to night"],
    howToUse: "Spray on pulse points: wrists, neck, and behind ears.",
    price: 58, originalPrice: 75, discount: 23,
    rating: 4.6, reviewCount: 2134,
    images: [img(132), img2(132)],
    videos: [],
    skinType: ["All"],
    productType: "Perfume", stock: 30, isNew: false, isBestSeller: true, isTrending: false, isFlashSale: false,
    tags: ["perfume", "jasmine", "floral", "fragrance"]
  },
  {
    id: "p33", name: "Multi-Peptide Eye Serum", brand: "RadianceCo",
    category: "Skincare", subCategory: "Eye Care",
    description: "Advanced multi-peptide eye serum that targets fine lines, crow's feet, and loss of firmness around the delicate eye area.",
    ingredients: "Peptide Complex, Matrixyl, Argireline, Hyaluronic Acid, Vitamin C",
    benefits: ["Reduces crows feet", "Firms eyelids", "Brightens", "Smooths lines"],
    howToUse: "Dot a small amount around the eye area. Gently tap with ring finger until absorbed. Use AM and PM.",
    price: 44, originalPrice: 58, discount: 24,
    rating: 4.5, reviewCount: 1678,
    images: [img(133), img2(133)],
    videos: [],
    skinType: ["All", "Normal", "Mature", "Dry"],
    productType: "Serum", stock: 35, isNew: true, isBestSeller: false, isTrending: false, isFlashSale: false,
    tags: ["eye serum", "peptide", "anti-aging", "firming"]
  },
  {
    id: "p34", name: "Deep Condition Hair Mask", brand: "BloomEssentials",
    category: "Hair Care", subCategory: "Treatments",
    description: "Intensive deep conditioning hair mask with shea butter and argan oil that restores moisture to dry, damaged hair.",
    ingredients: "Shea Butter, Argan Oil, Coconut Oil, Keratin, Vitamin B5",
    benefits: ["Deep conditioning", "Restores moisture", "Reduces frizz", "Adds shine"],
    howToUse: "Apply to clean damp hair. Leave for 15-20 minutes. Rinse thoroughly. Use weekly.",
    price: 22, originalPrice: 28, discount: 21,
    rating: 4.5, reviewCount: 1456,
    images: [img(134), img2(134)],
    videos: [],
    skinType: ["All"],
    productType: "Mask", stock: 50, isNew: false, isBestSeller: false, isTrending: false, isFlashSale: false,
    tags: ["hair mask", "deep conditioning", "shea butter", "damaged hair"]
  },
  {
    id: "p35", name: "Loose Setting Powder - Translucent", brand: "VelvetTouch",
    category: "Makeup", subCategory: "Face",
    description: "Ultra-fine translucent setting powder that blurs pores, controls shine, and sets makeup for a flawless airbrushed finish.",
    ingredients: "Silica, Mica, Zinc Stearate, Vitamin E, Jojoba Oil",
    benefits: ["Blurs pores", "Controls shine", "Airbrushed finish", "Invisible on skin"],
    howToUse: "Dip brush into powder, tap off excess, and dust over face focusing on T-zone.",
    price: 30, originalPrice: 38, discount: 21,
    rating: 4.5, reviewCount: 2890,
    images: [img(135), img2(135)],
    videos: [],
    skinType: ["All", "Oily", "Combination"],
    productType: "Powder", stock: 70, isNew: false, isBestSeller: true, isTrending: false, isFlashSale: false,
    tags: ["setting powder", "translucent", "matte", "blur"]
  },
]



